force-app/main/default/objects/Reader__c/Reader__c.object-meta.xml
<CustomObject>
    <description>A person who takes the book from library</description>
    <label>Reader</label>
    <nameField>
        <label>Reader Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Readers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>The reader can take many books. Subscription is a giving a book home. Person with a one-time subscription can&apos;t take books home. DaysOfHoldAllowed__c = 0 means reader hall</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Reader__c.field-meta.xml
<CustomField>
    <fullName>Reader__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Reader</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Reader__c.SubscriptionType__c</field>
            <operation>notEqual</operation>
            <value>&apos;one-time&apos;</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Reader__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Date when book was taken. Required Field</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/readerController.cls
public with sharing class readerController {
    @AuraEnabled(cacheable=true)
    public static List<Subscription__c> relatedBooks(String accountName) {
        return [SELECT id, StartDate__c FROM Subscription__c];
    }

    @AuraEnabled(cacheable=true)
    public static void getData(String accountName) {
        Httprequest req = new Httprequest();
        req.setMethod('GET');
        
        req.setEndpoint('https://avenga-school.herokuapp.com/retrieve-record');
        req.setHeader('objectName', 'Reader');
        req.setHeader('recordId', accountName);
        Http http = new Http();
                
        try {
            HTTPResponse res = http.send(req);
            Reader__c r = (Reader__c) JSON.deserialize(res.getBody(), Reader__c.class);
            r.Last_Sync_Date__c = System.now();
            r.ID = accountName;
            update r;
        }
        catch (System.CalloutException e){}
    }
}